name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    CARGO_TERM_COLOR: always

jobs:
    code_analysis:
        name: Code Analysis
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/
                      ~/.rustup/
                      target/
                  key: ${{ runner.os }}-cargo-{{ hashFiles('**/Cargo.lock') }}
            - name: Check with cargo-clippy
              run: cargo clippy --all-features -- -D warnings
            - name: Check with cargo-fmt
              run: cargo fmt --all --check

    tests:
        name: Tests
        needs: [code_analysis]
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v5
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/
                      ~/.rustup/
                      target/
                  key: ${{ runner.os }}-cargo-{{ hashFiles('**/Cargo.lock') }}
            - uses: taiki-e/install-action@nextest
            - name: Run all unit tests
              run: cargo nextest run --all-features
